# Generated by Django 5.0.7 on 2024-07-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_source', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving_name', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='name',
            new_name='expense_name',
        ),
    ]
